version: 2

sources:
  - name: tpch_sf100
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf100
    tables:
      - name: customer
      - name: nation
      - name: orders
      - name: part