version: 2

sources:
  - name: tpch_sf100
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf100
    tables:
      - name: customer
      - name: nation
      - name: orders
      - name: part
      - name: region

  - name: tpch_sf1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf1
    tables:
      - name: customer
      - name: nation
      - name: orders
      - name: part
      - name: region

  - name: source_data
    database: |
              {%- if target.name.upper() == "PRD" -%} SOURCE_PRD
              {%- elif target.name.upper() == "DEV" -%} SOURCE_DEV
              {%- else -%} SOURCE_DEV
              {%- endif -%}
    schema: schema_data
    tables:
      - name: customer