version: 2

sources:
  - name: tpch_sf100
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf100
    tables:
      - name: customer
      - name: nation
      - name: orders
      - name: part
      - name: region

  - name: tpch_sf1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf1
    tables:
      - name: customer
      - name: nation
      - name: orders
      - name: part
      - name: region

  - name: source_data
    database: source_dev
    schema: schema_data
    tables:
      - name: customer